#!/usr/bin/env bash

$REPO='controlgroup'

if [ -z "$1" ]
then
  echo "Usage: git cg-init projectName\n"
else
  echo "Creating local repo $1, setting remote to controlgroup/$1"
  git clone --depth 1 git@github.com:$REPO/cg-init.git $1
  
  cd $1
  rm -rf .git
  git init .
  git remote add origin git@github.com:$REPO/$1.git
  git add .
  git commit -a -m "First Commit"
  git push origin master
fi
